### ISSUE TITLE
Release Version 1.2.9 checklist

### ISSUE THREAD

**Issue by goneall** [OpenChain-Project/Online-Self-Certification-Web-App#195]
- [ ] ~~Resolve issue #193 Change PDF link on the index page to point to the main web page~~
- [x] Resolve issue #192 Add ISO specification information to conformance web app version
- [x] Resolve issue #191 Add company name and spec version to the conforming application submission email
- [x] Resolve issue #190 Move or remove the conforming submissions from the Web App
- [x] Resolve issue #189 Section titles are not updated when the questionnaire is updated
- [x] Resolve issue #188 Add translation for Japanese "Yes"
- [x] Resolve issue #173 Questionnaire update fails when section names change
- [x] Add language button to questionnaire page
- [x] Review Korean translation for "Change Language"
- [x] Review Japanese translation for "Change Language"
- [x] Bump version number in app
- [x] Update the app in AWS
- [x] Update the questionnaire including the updated Korean and Japanese text
- [x] verify above issues have been resolved

**Comment by goneall** [comment]
Release has been updated successfully
