### ISSUE TITLE
Release version 1.2.10 Checklist

### ISSUE THREAD

**Issue by goneall** [OpenChain-Project/Online-Self-Certification-Web-App#196]
- [x] Resolve issue #194 Additional Languages
- [x] Update PDF link to point to official website
- [x] Bump version
- [x] Deploy on AWS
- [x] Update questionnaire from the questionnaire repo containing the additional languages
- [x] Verify additional languages in drop down
