### ISSUE TITLE
Release 1.2.13 checklist

### ISSUE THREAD

**Issue by goneall** [OpenChain-Project/Online-Self-Certification-Web-App#215]
- [x] Add recaptcha for signup
- [x] Add recaptcha for login
- [x] Add recaptcha for password reset
- [x] Add check for resend verification - only one verification resend per day
- [x] Add recaptcha for email password reset
- [x] Add recaptcha for verification email click
- [x] Add logging for forwarded IP addresses
- [x] Test recaptcha for signup
- [x] Test recaptcha for login
- [x] Test recaptcha for password reset
- [x] Test resend verifications less than one day
- [x] Test resend verification > 1 day
- [x] Deploy
- [x] Test email password reset recaptcha
- [x] test verification email recaptcha
- [x] Review logs to make sure forwarded IP addresses are logged
- [x] Implement web application firewall
- [x] Notify Amazon that all issues have been addressed
